# Generated by Django 2.2.4 on 2019-10-08 09:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prixm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prixl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descf', models.TextField()),
                ('descb', models.TextField()),
                ('pimage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
